# Generated by Django 4.0.5 on 2022-06-10 11:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tile', models.CharField(max_length=150)),
                ('body', models.TextField()),
                ('image', models.ImageField(upload_to='media/images')),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
